version: "3.9"  # optional since v1.27.0
services:
  publicapi:
    build: 
      context: ./publicAPI/
    ports:
      - "80:3000"
    networks:
      - public
      - backend


networks:
  public:
  backend: