version: "3.9"
services:
  frontend:
    build:
      context: ./frontend/
    restart: always
    ports:
      - 80:80
    networks:
      - public

  publicapi:
    build:
      context: ./publicAPI/
    restart: always
    ports:
      - 3000:3000
    networks:
      - public
      - backend

  mlclassifier:
    build:
      context: ./mlClassifier/
    restart: always
    environment:
      PORT: 3000
    networks:
      - backend

  hCode_colorizer:
    build:
      context: ./hCode_colorizer/
    restart: always
    environment:
      PORT: 3030
    networks:
      - backend

  formalsyntaxhighlighter:
    build:
      context: ./formalSyntaxHighlighter/
    restart: always
    networks:
      - backend

  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - backend

  #adminer to be able to access  database
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    networks:
      - public
      - backend

networks:
  public:
  backend:
