version: "3.9"
services:
  frontend:
    build:
      context: ./frontend/
    restart: always
    ports:
      - 80:80
    networks:
      - public

  publicapi:
    build:
      context: ./publicAPI/
    restart: always
    ports:
      - 3000:3000
    networks:
      - public
      - backend

  mlclassifier:
    build:
      context: ./mlClassifier/
    restart: always
    environment:
      PORT: 3000
    networks:
      - backend
    volumes:
      - ./mlClassifier:/app

  hcode_colorizer:
    build:
      context: ./hCode_colorizer/
    restart: always
    environment:
      PORT: 3030
    networks:
      - backend

  formalsyntaxhighlighter:
    build:
      context: ./formalSyntaxHighlighter/
    restart: always
    networks:
      - backend


networks:
  public:
  backend:
