name: Docker build

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    test:
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2

        - name: Build docker containers
          run: |
            docker-compose build
