name: Docker build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [ review_requested, ready_for_review ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build docker containers
      run: |
        docker-compose build
