name: hCode Colorzier Test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9.7-bullseye
    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        cd hCode_colorizer
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd hCode_colorizer
        pytest --cache-clear --cov="." > pytest-coverage.txt

    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: hCode_colorizer/pytest-coverage.txt