name: ML Classifier Lint

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9.7-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          cd mlClassifier
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing the code with pylint and Black
        run: |
          cd mlClassifier          
          pylint --fail-under=10 test_app.py app.py
          black --check test_app.py app.py