name: Frontend test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [ review_requested, ready_for_review ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test frontend
      run: |
        cd frontend
        npm i 
        npm run build:ci
        npm run test:ci
