name: Frontend test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test frontend
      run: |
        cd frontend
        npm i 
        npm run build:ci
        npm run test:ci

    - name: Monitor coverage
      uses: slavcodev/coverage-monitor-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage_path: "frontend/coverage/frontend/coverage-summary.json"
        threshold_alert: 50
        threshold_warning: 80
        threshold_metric: "statements"
        status_context: "Frontend coverage"
        comment_context: "Frontend coverage"
        comment_mode: "replace"
        comment_footer: false
