name: Syntax Highlighter Lint

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: gradle:7-jdk17
    steps:
    - uses: actions/checkout@v2
  
    - name: lint Syntax Highlighter
      run: |
        cd formalSyntaxHighlighter
        gradle spotlessCheck --no-daemon