name: Test Syntax Highlighter

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: gradle:7-jdk17
    steps:
    - uses: actions/checkout@v2
  
    - name: test Syntax Highlighter
      run: |
        cd formalSyntaxHighlighter
        gradle test --no-daemon
        gradle jacocoTestReport --no-daemon

    - name: Monitor coverage
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: formalSyntaxHighlighter/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 90
        title: "Syntax Highlighter Coverage"